#!/bin/sh

set -e

config="$XDG_CONFIG_HOME"
if [ -z "$config" ]; then
	config="$HOME/.config"
fi
config="$config/org-agent/config.yaml"

wasmtime \
	--dir "$HOME/tasks" \
	-S allow-ip-name-lookup \
	-S inherit-network \
	--invoke "run(\"\", $(yq -o json "$config" | jq -Rs))" \
	"$0"
