#!/bin/sh

set -e

config="$XDG_CONFIG_HOME"
if [ -z "$config" ]; then
	config="$HOME/.config"
fi
config="$config/org-agent/config.yaml"

rm -f /tmp/org-agent.fifo
mkfifo /tmp/org-agent.fifo
echo "Initial prompt:" > $HOME/tasks/knowledge.prompt

wasmtime \
	--dir "$HOME/tasks" \
	-S allow-ip-name-lookup \
	-S inherit-network \
	--invoke "run(\"\", $(yq -o json "$config" | jq -Rs))" \
	/usr/lib/org_agent.wasm < /tmp/org-agent.fifo
